#!/usr/bin/env bash

function install_openresty {
  curl https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz -o openresty-${OPENRESTY_VERSION}.tar.gz
  
  tar xvfz openresty-${OPENRESTY_VERSION}.tar.gz
  pushd openresty-${OPENRESTY_VERSION}
  ./configure -j2 --prefix="$shome/vendor/install-${OPENRESTY_VERSION}" --with-cc-opt="-I$PKG_HOME/install/include" --with-ld-opt="-L$PKG_HOME/install/lib" \
    --with-pcre-jit \
    --with-ipv6 \
    --with-http_realip_module \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_v2_module
  gmake build
  gmake install
  popd
}

function install_luarocks {
  curl http://luarocks.github.io/luarocks/releases/luarocks-${LUAROCKS_VERSION}.tar.gz -o luarocks-${LUAROCKS_VERSION}.tar.gz
  tar xvfz luarocks-${LUAROCKS_VERSION}.tar.gz
  pushd luarocks-${LUAROCKS_VERSION}
  ./configure \
    --prefix="$shome/vendor/install-luarocks-${LUAROCKS_VERSION}" \
    --lua-suffix=jit \
    --with-lua="$shome/vendor/openresty/luajit" \
    --with-lua-include="$shome/vendor/openresty/luajit/include/luajit-2.1"
  gmake
  gmake install
  popd
}

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  mkdir -p "$shome/bin" "$shome/vendor"
  cd "$shome/vendor"

  set -x

  local pth_install_openresty="$shome/vendor/install-${OPENRESTY_VERSION}"
  local pth_install_luarocks="$shome/vendor/install-luarocks-${LUAROCKS_VERSION}"

  rm -rf openresty-${OPENRESTY_VERSION} openresty-${OPENRESTY_VERSION}.tar.gz
  rm -rf luarocks-${LUAROCKS_VERSION} luarocks-${LUAROCKS_VERSION}.tar.gz

  if ! cache location "$pth_install_openresty"; then
    install_openresty
    cache location archive "$pth_install_openresty"
  fi

  ln -nfs "install-${OPENRESTY_VERSION}" "$shome/vendor/openresty"
  ln -nfs "$(which luajit)" "$shome/bin/lua"
  
  if ! cache location "$pth_install_luarocks"; then
    install_luarocks
    cache location archive "$pth_install_luarocks"
  fi

  ln -nfs "install-luarocks-${LUAROCKS_VERSION}" "$shome/vendor/luarocks"

  set +f
  rm -rf openresty-${OPENRESTY_VERSION} openresty-${OPENRESTY_VERSION}.tar.gz*
  rm -rf luarocks-${LUAROCKS_VERSION} luarocks-${LUAROCKS_VERSION}.tar.gz*

  pkg ensure nginx www/nginx-devel
}

main "$@"
