#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  shift
  export LD_LIBRARY_PATH="$PKG_HOME/install/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
  exec openresty -g 'daemon off;' "$@"
}

main "$@"

