#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_openresty="0.0.1"
  jq -n --arg openresty "$ver_openresty" '{openresty: $openresty}'
}

version "$@"
