#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_openresty="$(openresty -v 2>&1 | cut -d/ -f2 || true)"
  jq -n --arg openresty "$ver_openresty" '{openresty: $openresty}'
}

version "$@"
